# """
# Django settings for core project.

# Generated by 'django-admin startproject' using Django 6.0.2.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """

# from pathlib import Path
# from datetime import timedelta

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-f44v=7rl^^^&e5s5clm)axsv!!u-pcmm4aej!d_j5nf*lh6ajt'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
    
#      # third-party
#     'rest_framework',
#     'corsheaders',
    
#     # local
#     'designs',
#     'accounts',
#     'finance'
# ]

# # ========================
# # Django REST Framework
# # ========================

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticatedOrReadOnly',
#     ],
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ],
# }

# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

#     "ROTATE_REFRESH_TOKENS": True,
#     "BLACKLIST_AFTER_ROTATION": True,

#     "AUTH_HEADER_TYPES": ("Bearer",),

#     "USER_ID_FIELD": "id",
#     "USER_ID_CLAIM": "user_id",
# }


# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',  
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
# ]

# # تنظیمات CORS برای توسعه
# CORS_ALLOW_ALL_ORIGINS = True  # فقط برای توسعه

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     # در برخی موارد، ممکن است نیاز باشد 127.0.0.1 را نیز اضافه کنید.
#     "http://127.0.0.1:5173",
# ]


# ROOT_URLCONF = 'core.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'core.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]




# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'
# AUTH_USER_MODEL = 'accounts.User'

# import os 
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# import os
# from pathlib import Path
# import logging.config

# BASE_DIR = Path(__file__).resolve().parent.parent

# LOG_DIR = os.path.join(BASE_DIR, "logs")
# os.makedirs(LOG_DIR, exist_ok=True)

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,

#     "formatters": {
#         "verbose": {
#             "format": "[{levelname}] {asctime} | {name} | {module}:{lineno} → {message}",
#             "style": "{",
#         },
#         "simple": {
#             "format": "{levelname}: {message}",
#             "style": "{",
#         },
#         "finance": {
#             "format": "{asctime} | user={user} | action={action} | message={message}",
#             "style": "{",
#         }
#     },

#     "handlers": {
#         # ---- Console for dev ----
#         "console": {
#             "class": "logging.StreamHandler",
#             "formatter": "verbose",
#         },

#         # ---- General Log File ----
#         "file_general": {
#             "class": "logging.FileHandler",
#             "filename": os.path.join(LOG_DIR, "backend.log"),
#             "formatter": "verbose",
#             "encoding": "utf-8",
#         },

#         # ---- Financial Transaction Logs ----
#         "file_finance": {
#             "class": "logging.FileHandler",
#             "filename": os.path.join(LOG_DIR, "finance.log"),
#             "formatter": "verbose",
#             "encoding": "utf-8",
#         },

#         # ---- Errors Only ----
#         "file_errors": {
#             "class": "logging.FileHandler",
#             "filename": os.path.join(LOG_DIR, "errors.log"),
#             "formatter": "verbose",
#             "level": "ERROR",
#             "encoding": "utf-8",
#         },
#     },

#     "loggers": {
#         # Main Django logger
#         "django": {
#             "handlers": ["console", "file_general"],
#             "level": "INFO",
#             "propagate": True,
#         },

#         # Your app logs
#         "designs": {
#             "handlers": ["console", "file_general"],
#             "level": "INFO",
#             "propagate": False,
#         },

#         # Financial logs
#         "finance": {
#             "handlers": ["console", "file_finance"],
#             "level": "INFO",
#             "propagate": False,
#         },

#         # Errors
#         "errors": {
#             "handlers": ["file_errors"],
#             "level": "ERROR",
#             "propagate": False,
#         },
#     }
# }

# # SMS.ir Configuration
# SMSIR_API_KEY = "zqztrXlxVSn6US870MztEofsMTucjtl36ciWrhHUT73Pry0r"
# SMSIR_LINE_NUMBER = "30002128093854"  # شماره خط اختصاصی شما

# # افزایش محدودیت حجم آپلود
# DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 مگابایت
# FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 مگابایت
# # ================setting docker==============================

"""
Django settings for core project.
"""

from pathlib import Path
from datetime import timedelta
import os
import secrets
from dotenv import load_dotenv

# بارگذاری متغیرهای محیطی
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ========================
# تولید SECRET_KEY امن به صورت خودکار
# ========================
def get_secret_key():
    """تولید کلید امن 64 کاراکتری اگر در env نباشد"""
    secret = os.environ.get('SECRET_KEY')
    if secret:
        return secret
    # اگر کلید در env نبود، یک کلید امن تصادفی تولید کن
    return secrets.token_urlsafe(64)

SECRET_KEY = get_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # third-party
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    
    # local
    'designs',
    'accounts',
    'finance'
]

# ========================
# Django REST Framework
# ========================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost",
    "http://your-domain.com",
]

if not DEBUG:
    CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
if os.environ.get('USE_POSTGRES', 'False') == 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'bizcard_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres123'),
            'HOST': os.environ.get('DB_HOST', 'db'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================
# Logging Configuration
# ========================

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} | {name} | {module}:{lineno} → {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname}: {message}",
            "style": "{",
        },
        "finance": {
            "format": "{asctime} | user={user} | action={action} | message={message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file_general": {
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "backend.log"),
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "file_finance": {
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "finance.log"),
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "file_errors": {
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "errors.log"),
            "formatter": "verbose",
            "level": "ERROR",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file_general"],
            "level": "INFO",
            "propagate": True,
        },
        "designs": {
            "handlers": ["console", "file_general"],
            "level": "INFO",
            "propagate": False,
        },
        "finance": {
            "handlers": ["console", "file_finance"],
            "level": "INFO",
            "propagate": False,
        },
        "errors": {
            "handlers": ["file_errors"],
            "level": "ERROR",
            "propagate": False,
        },
    }
}

# ========================
# SMS.ir Configuration
# ========================
SMSIR_API_KEY = os.environ.get('SMSIR_API_KEY', '')
SMSIR_LINE_NUMBER = os.environ.get('SMSIR_LINE_NUMBER', '')